Project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, BooleanField, StringField, PasswordField
from wtforms.validators import DataRequired, ValidationError, EqualTo
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from Project.models import User


class RegistrationForm(FlaskForm):
    name = StringField('Name', [DataRequired()])
    email = StringField('Email', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])
    confirm_password = PasswordField("Confirm Password", [EqualTo('password', "Passwords needs to match.")])
    submit = SubmitField('Register')

    def verify_name(self, name):
        user = User.query.filter_by(name=name.data).first()
        if user:
            raise ValidationError('This name is not valid.Please enter another name.')

    def verify_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('This email is not valid.Please enter another name.')


class LoginForm(FlaskForm):
    email = StringField('Email', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])
    remember = BooleanField("Keep me logged in")
    submit = SubmitField('Prisijungti')

class UserUpdateForm(FlaskForm):
    name = StringField('Name', [DataRequired()])
    email = StringField('Email', [DataRequired()])
    picture = FileField('Update profile picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def verify_name(self, name):
        if name.data != current_user.name:
            user = User.query.filter_by(name=name.data).first()
            if user:
                raise ValidationError('This name is not valid.Please enter another name.')

    def verify_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('This email is not valid.Please enter another name.')

Project/users/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import current_user, logout_user, login_user, login_required
from Project.users.forms import RegistrationForm, LoginForm, UserUpdateForm
from Project.models import User
from Project.users.utils import save_picture
from Project import db, bcrypt


users = Blueprint('users', __name__)

@users.route("/registration", methods=['GET', 'POST'])
def registration():
    db.create_all()
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, email=form.email.data, password=password_hash)
        db.session.add(user)
        db.session.commit()
        flash('Registration Successful!', 'success')
        return redirect(url_for('main.index'))
    return render_template('registration.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash("You entered an invalid Login Name and/or Password combination. Please verify that you entered this information correctly!", 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route("/user", methods=['GET', 'POST'])
@login_required
def user():
    form = UserUpdateForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture = save_picture(form.picture.data)
            current_user.picture = picture
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Was Updated!', 'success')
        return redirect(url_for('users.user'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.email.data = current_user.email
    picture = url_for('static', filename='pictures/' + current_user.picture)
    return render_template('user.html', title='Account', form=form, picture=picture)

Project/views/routes.py
from flask import render_template, redirect, url_for, flash, Blueprint
from flask_login import current_user
from Project.views.forms import PatientForm, NotesForm
from Project.models import Patients, Notes
from Project import db

views = Blueprint('views', __name__)

@views.route('/dashboard')
def posts():
    posts = Patients.query.order_by(Patients.date_posted)
    return render_template('dashboard.html', posts=posts)

@views.route('/dashboard/<int:id>')
def post(id):
    post = Patients.query.get(id)
    return render_template("patient.html", post=post)

@views.route('/add_patient', methods=['GET', 'POST'])
def add_patient():
    form = PatientForm()
    if form.validate_on_submit():
        planner = current_user.id
        patient = Patients(name = form.name.data, surname = form.surname.data, email = form.email.data, phone = form.phone.data,  relationship = form.relationship.data, treatment=form.treatment.data, user_id=planner)
        # clear the form
        form.name.data=''
        form.surname.data=''
        form.email.data=''
        form.phone.data=''
        form.relationship.data=''
        form.treatment.data=''
        db.session.add(patient)
        db.session.commit()
        flash("Data Submitted Successfully!")
    return render_template("add_patient.html", form=form)

@views.route('/dashboard/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    post = Patients.query.get(id)
    form = PatientForm()
    if form.validate_on_submit():
        post.name = form.name.data
        post.surname = form.surname.data
        post.email = form.email.data
        post.phone = form.phone.data
        post.relationship = form.relationship.data
        post.treatment = form.treatment.data
        # update database
        db.session.add(post)
        db.session.commit()
        flash("Post has been updated!")
        return redirect(url_for('views.posts', id=post.id))
    form.name.data=post.name
    form.surname.data=post.surname
    form.email.data=post.email
    form.phone.data=post.phone
    form.relationship.data=post.relationship
    form.treatment.data=post.treatment
    return render_template("update.html", form=form)

@views.route('/dashboard/delete/<int:id>')
def delete(id):
    delete = Patients.query.get(id)
    db.session.delete(delete)
    db.session.commit()
    return redirect(url_for('views.posts'))

@views.route('/notes')
def notes():
    # get all notes in one place
    notes = Notes.query.order_by(Notes.date_posted)
    return render_template("notes.html", notes=notes)

@views.route('/notes/<int:id>')
def note(id):
    note = Notes.query.get(id)
    return render_template("note.html", note=note)

@views.route('/add_note', methods=['GET', 'POST'])
def add_notes():
    form = NotesForm()
    if form.validate_on_submit():
        note = Notes(sender=form.sender.data,receiver=form.receiver.data, notes=form.notes.data)
        # clear the form
        form.sender.data=''
        form.receiver.data=''
        form.notes.data=''
        db.session.add(note)
        db.session.commit()
        flash("Data Submitted Successfully!")
    return render_template("add_note.html", form=form)

@views.route('/notes/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    note = Notes.query.get(id)
    form = NotesForm()
    if form.validate_on_submit():
        note.sender = form.sender.data
        note.receiver = form.receiver.data
        note.notes = form.notes.data
        # update database
        db.session.add(note)
        db.session.commit()
        flash("Post has been updated!")
        return redirect(url_for('views.notes', id=note.id))
    form.sender.data=note.sender
    form.receiver.data=note.receiver
    form.notes.data=note.notes
    return render_template("edit.html", form=form)

@views.route('/notes/delete/<int:id>')
def delete2(id):
    delete2 = Notes.query.get(id)
    db.session.delete(delete2)
    db.session.commit()
    return redirect(url_for('views.notes'))

Project/templates/add_note.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Notes: </h1>

<form method="POST">
    {{ form.hidden_tag()}}
    <div class="form-group">
        {{form.sender.label(class="form-control-label")}}
        {{form.sender(class="form-control")}}
    </div><div class="form-group">
        {{form.receiver.label(class="form-control-label")}}
        {{form.receiver(class="form-control")}}
    </div><div class="form-group">
        {{form.notes.label(class="form-control-label")}}
        {{form.notes(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.submit(class="btn btn-dark")}}
    </div>
</form>

{% endblock %}

Project/templates/add_patient.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Patient Registration: </h1>

<form method="POST">
    {{ form.hidden_tag()}}
    <div class="form-group">
        {{form.name.label(class="form-control-label")}}
        {{form.name(class="form-control")}}
    </div><div class="form-group">
        {{form.surname.label(class="form-control-label")}}
        {{form.surname(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class="form-control")}}
    </div><div class="form-group">
        {{form.phone.label(class="form-control-label")}}
        {{form.phone(class="form-control")}}
    </div><div class="form-group">
        {{form.relationship.label(class="form-control-label")}}
        {{form.relationship(class="form-control")}}
    </div><div class="form-group">
        {{form.treatment.label(class="form-control-label")}}
        {{form.treatment(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.submit(class="btn btn-dark")}}
    </div>
</form>

{% endblock %}

Project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Physioterapy records system</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
</head>
<body>
 <h1> Physioterapy records system </h1>
<div class = 'navbar navbar-expand-lg navbar-dark bg-dark'>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            <a class="nav-item nav-link" id="index" href="/">Home</a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" id="dashboard" href="/dashboard">Dashboard</a>
            <a class="nav-item nav-link" id="add_patient" href="/add_patient">Add Patient</a>
            <a class="nav-item nav-link" id="notes" href="/notes">Notes</a>
            <a class="nav-item nav-link" id="add_note" href="/add_note">Add Note</a>
             <a class="nav-item nav-link" id="user" href="/user">User</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="registration" href="/registration">Registration</a>
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            {% endif%}
        </div>
    </div>
</div>
 <div>

 </div>

{%block content%}

{% endblock%}
</body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



</html>

Project/templates/dashboard.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Patient list: </h1>

{% for post in posts %}
<div class="shadow p-3 mb-5 bg-body rounded">
    Date: {{post.date_posted}}<br>
    By: {{post.planner.name}}<br>
    Name: {{post.name}}<br>
    Surname: {{post.surname}}<br>
    Email: {{post.email}}<br>
    Phone number: {{post.phone}}<br>
    Next of Kin: {{post.relationship}}<br>
    Treatment plan: {{post.treatment}}<br> <br>
    <a href="{{url_for('views.post', id=post.id)}}" class="btn btn-dark">View patient</a>
    <a href="{{url_for('views.update', id=post.id)}}" class="btn btn-dark">Update</a>
    <a href="{{url_for('views.delete', id=post.id)}}" class="btn btn-dark">Delete</a>
</div>
<br>
{% endfor%}

{% endblock %}

Project/templates/edit.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Notes: </h1>

<form method="POST">
    {{ form.hidden_tag()}}
    <div class="form-group">
        {{form.sender.label(class="form-control-label")}}
        {{form.sender(class="form-control")}}
    </div><div class="form-group">
        {{form.receiver.label(class="form-control-label")}}
        {{form.receiver(class="form-control")}}
    </div><div class="form-group">
        {{form.notes.label(class="form-control-label")}}
        {{form.notes(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.submit(class="btn btn-dark")}}
    </div>
</form>

<a href="{{ url_for('views.notes')}}" class="btn btn-dark">Back To Notes</a>

{% endblock %}

Project/templates/index.html
{% extends "base.html" %}
{% block content %}
<br>
<h1>Welcome!</h1>

{% endblock %}

Project/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Prisijunkite</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark") }}
            </div>
        </form>
    </div>

{% endblock %}

Project/templates/note.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Note: </h1>

<div class="shadow p-3 mb-5 bg-body rounded">
    Date: {{note.date_posted}}<br>
    From: {{note.sender}}<br>
    To: {{note.receiver}}<br>
    Note: {{note.notes}}<br> <br>
</div>

<a href="{{url_for('views.notes')}}" class="btn btn-dark">Back to Notes</a>

{% endblock %}

Project/templates/notes.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Notes: </h1>

{% for note in notes %}
<div class="shadow p-3 mb-5 bg-body rounded">
    Date: {{note.date_posted}}<br>
    From: {{note.sender}}<br>
    To: {{note.receiver}}<br>
    Note: {{note.notes}}<br> <br>
    <a href="{{url_for('views.note', id=note.id)}}" class="btn btn-dark">View note</a>
    <a href="{{url_for('views.edit', id=note.id)}}" class="btn btn-dark">Update</a>
    <a href="{{url_for('views.delete2', id=note.id)}}" class="btn btn-dark">Delete</a>
</div>
<br>
{% endfor%}

{% endblock %}

Project/templates/patient.html
{% extends "base.html" %}
{% block content %}

<!--{% for message in get_flashed_messages() %}-->
<!--    <div class="alert alert-warning alert-dismissable fade show" role="alert">-->
<!--        {{message}}-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--    </div>-->
<!--{% endfor %}-->

<h1>Patient: </h1>


<div class="shadow p-3 mb-5 bg-body rounded">
    Date: {{post.date_posted}}<br>
    Name: {{post.name}}<br>
    Surname: {{post.surname}}<br>
    Email: {{post.email}}<br>
    Phone number: {{post.phone}}<br>
    Next of Kin: {{post.relationship}}<br>
    Treatment plan: {{post.treatment}}<br>
</div>

<a href="{{url_for('views.posts')}}" class="btn btn-dark">Back to List</a>

{% endblock %}

Project/templates/registration.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Registration</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark") }}
            </div>
        </form>
    </div>

{% endblock %}

Project/templates/update.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {{ form.hidden_tag()}}
    <div class="form-group">
        {{form.name.label(class="form-control-label")}}
        {{form.name(class="form-control")}}
    </div><div class="form-group">
        {{form.surname.label(class="form-control-label")}}
        {{form.surname(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class="form-control")}}
    </div><div class="form-group">
        {{form.phone.label(class="form-control-label")}}
        {{form.phone(class="form-control")}}
    </div><div class="form-group">
        {{form.relationship.label(class="form-control-label")}}
        {{form.relationship(class="form-control")}}
    </div><div class="form-group">
        {{form.treatment.label(class="form-control-label")}}
        {{form.treatment(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.submit(class="btn btn-dark")}}
    </div>
</form>

<a href="{{ url_for('views.posts')}}" class="btn btn-dark">Back To List</a>

{% endblock %}

Project/templates/user.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">User information</legend>
            <img class="rounded-circle account-img" src="{{ picture }}">
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                {{ form.name(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
        </div>
    </form>
</div>
{% endblock %}